// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `connected_client`, `handle_direct_function_result`, `internal_action`, `internal_mutation`, `internal_set_auth`, `internal_subscribe`, `new`, `parse_json_args`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AuthErrorStreamReceiver>>
abstract class AuthErrorStreamReceiver implements RustOpaqueInterface {
  /// Receives the next auth error from the stream.
  /// Returns None if the stream is closed.
  Future<AuthError?> recv();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CallbackSubscriber>>
abstract class CallbackSubscriber
    implements RustOpaqueInterface, QuerySubscriber {
  @override
  Future<void> onError({required String message, String? value});

  @override
  Future<void> onUpdate({required String value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CallbackSubscriberDartFn>>
abstract class CallbackSubscriberDartFn
    implements RustOpaqueInterface, QuerySubscriber {
  @override
  Future<void> onError({required String message, String? value});

  @override
  Future<void> onUpdate({required String value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileConvexClient>>
abstract class MobileConvexClient implements RustOpaqueInterface {
  /// Executes an action on the Convex backend.
  Future<String> action({
    required String name,
    required Map<String, String> args,
  });

  /// Executes a mutation on the Convex backend.
  Future<String> mutation({
    required String name,
    required Map<String, String> args,
  });

  /// Creates a new MobileConvexClient instance with the given deployment URL and client ID.
  factory MobileConvexClient({
    required String deploymentUrl,
    required String clientId,
  }) => RustLib.instance.api.crateMobileConvexClientNew(
    deploymentUrl: deploymentUrl,
    clientId: clientId,
  );

  /// Executes a query on the Convex backend.
  Future<String> query({
    required String name,
    required Map<String, String> args,
  });

  /// Registers an auth error callback. Returns a stream receiver for auth errors.
  /// When an auth error occurs, it will be sent through this stream.
  /// Dart should call `respond_to_auth_error` with the appropriate action.
  Future<AuthErrorStreamReceiver> registerAuthErrorHandler();

  /// Responds to an auth error with the specified action.
  /// This should be called after receiving an auth error through the stream.
  void respondToAuthError({required AuthErrorAction action});

  /// Sets authentication token for the client.
  Future<void> setAuth({String? token});

  /// Subscribes to real-time updates from a Convex query.
  Future<SubscriptionHandle> subscribe({
    required String name,
    required Map<String, String> args,
    required FutureOr<void> Function(String) onUpdate,
    required FutureOr<void> Function(String, String?) onError,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SubscriptionHandle>>
abstract class SubscriptionHandle implements RustOpaqueInterface {
  /// Cancels the subscription by sending a cancellation signal.
  void cancel();
}

abstract class QuerySubscriber {
  Future<void> onError({required String message, String? value});

  Future<void> onUpdate({required String value});
}

/// Authentication error information from the Convex backend.
/// Exposed to Dart when an authentication error occurs.
class AuthError {
  /// The error message describing why authentication failed.
  final String errorMessage;

  /// The base version of the identity that was rejected, if available.
  final int? baseVersion;

  const AuthError({required this.errorMessage, this.baseVersion});

  @override
  int get hashCode => errorMessage.hashCode ^ baseVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthError &&
          runtimeType == other.runtimeType &&
          errorMessage == other.errorMessage &&
          baseVersion == other.baseVersion;
}

@freezed
sealed class AuthErrorAction with _$AuthErrorAction {
  const AuthErrorAction._();

  /// Refresh authentication with a new token.
  const factory AuthErrorAction.refreshToken({required String token}) =
      AuthErrorAction_RefreshToken;

  /// Clear authentication and continue as unauthenticated.
  const factory AuthErrorAction.clearAuth() = AuthErrorAction_ClearAuth;

  /// Disconnect the client entirely.
  const factory AuthErrorAction.disconnect() = AuthErrorAction_Disconnect;
}

@freezed
sealed class ClientError with _$ClientError implements FrbException {
  const ClientError._();

  /// An internal error within the mobile Convex client.
  const factory ClientError.internalError({required String msg}) =
      ClientError_InternalError;

  /// An application-specific error from a remote Convex backend function.
  const factory ClientError.convexError({required String data}) =
      ClientError_ConvexError;

  /// An unexpected server-side error from a remote Convex function.
  const factory ClientError.serverError({required String msg}) =
      ClientError_ServerError;
}
